### ISSUE TITLE
Bad gateway at login (0.8.1)

### ISSUE THREAD

**Issue by ams3401** [hassio-addons/addon-nginx-proxy-manager#123]
![1342](https://user-images.githubusercontent.com/70864968/97126777-6f9c8e00-16fd-11eb-949b-80367a7682cf.JPG)

Same issue as [#117 ](https://github.com/hassio-addons/addon-nginx-proxy-manager/issues/117) but on 0.8.1.
It started throwing "Bad gateway" on 0.8.0, so I reinstalled, same issue, then I updated to 0.8.1, and still the same.

`[26/Oct/2020:02:04:22 +0000] 400 - - http localhost-nginx-proxy-manager "-" [Client 172.104.242.173] [Length 150] [Gzip -] "-" "-"
2020/10/26 02:06:20 [error] 581#581: *29 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.29, server: nginxproxymanager, request: "POST /api/tokens HTTP/1.1", upstream: "http://127.0.0.1:3000/tokens", host: "192.168.1.30:81", referrer: "http://192.168.1.30:81/login"`

**Comment by frenck** [comment]
I believe this was resolved on Discord?

**Comment by ams3401** [comment]
> I believe this was resolved on Discord?

Sorry I’m not in the channel and I think it would be helpful if the solution or news is posted here too

**Comment by FaserF** [comment]
I am also getting similar issues.
![image](https://user-images.githubusercontent.com/12374134/97710944-b6eb9b80-1abc-11eb-9ca4-2912cc17b5a0.png)

The second error when still trying to log in:
![image](https://user-images.githubusercontent.com/12374134/97710976-c10d9a00-1abc-11eb-8740-398c72d7af00.png)

Sometimes I get this issue:
![image](https://user-images.githubusercontent.com/12374134/97710989-c66ae480-1abc-11eb-9ff9-df9d5f0cd4dd.png)


What I tried:
- restarting my raspberry pi 4
- reinstalled the addon 3 times
- checked the logs (unfortunatly nothing is there)
- the port is ready

**Comment by flochtililoch** [comment]
I've had this issue after re-installing home assistant and NPM. Clearing cookies solved it for me.

**Comment by FaserF** [comment]
Issue still exists for me. Latest HA, Latest HA OS. Addon reinstalled.
I really dont know thats the issue.

**Comment by frenck** [comment]
@FaserF No, it will not be removed, as the data is stored in an external database (the MariaDB add-on).
